dist: bionic

services:
  - mysql
  - redis

language: node_js
node_js:
  - 11

notifications:
  email:
    on_success: never
    on_failure: change

before_install:
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('dockerpass') where User='root'; FLUSH PRIVILEGES;"
  - sudo systemctl restart mysql
  - mysql -pdockerpass -e 'CREATE DATABASE dockertest;'
  - cp .env.orig .env
  - sed -i 's/added_at_build_time/'"$YOUTUBE_API_KEY"'/g' .env.test

install:
  - npm i

before_script:
  - npx cross-env NODE_ENV=testing knex migrate:latest

script:
  - npm run test
