version: '3'
services:
  db:
    image: 'mysql:5.7'
    volumes:
      - 'db_data:/var/lib/mysql'
    restart: on-failure
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: dockerpass
      MYSQL_DATABASE: dockerdb
      MYSQL_USER: m4v1
      MYSQL_PASSWORD: dockerpass
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
volumes:
  db_data: null
